[package]
name = "toy_c_build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cuda-sys = "0.2.0"

[build-dependencies]
bindgen = "0.63.0"
cc = "1.0.79"
glob = "0.3.1"
